export const SEARCH_ARTICLES = 'SEARCH_ARTICLES';
export const CLEAR_ARTICLES = 'CLEAR_ARTICLES';
export const SET_LOADING = 'SET_LOADING';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const SET_ALERT = 'SET_ALERT';
export const GET_TOP_ARTICLES = 'GET_TOP_ARTICLES';
